PracticaMVC/Models/ErrorViewModel.cs
namespace PracticaMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMVC.Models;
using System.Diagnostics;

namespace PracticaMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaMVC/Controllers/vistaRazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace PracticaMVC.Controllers
{
    public class vistaRazorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult bloqueMultiple()
        {
            return View();
        }

        public IActionResult condiciones()
        {
            return View();
        }

        public IActionResult bucles()
        {
            return View();
        }
    }
}

PracticaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="vistaRazor" asp-action="bloqueMultiple">Bloque Múltiple</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="vistaRazor" asp-action="condiciones">Condiciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="vistaRazor" asp-action="bucles">Bucles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PracticaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMVC/Views/vistaRazor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Index</h2>

<div>
    <label> Fecha actual: @DateTime.Now.ToString(); </label> <br/>
    <label> Fecha larga actual: @DateTime.Now.ToLongDateString(); </label> <br />
    <label> Adición de números: @(250+250); </label>
</div>

PracticaMVC/Views/vistaRazor/bloqueMultiple.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var num1 = 100;
    var num2 = 200;
    var num3 = num1 + num2;
    string message = "Bienvenido, ejemplo de bloque multiple";
}

<label>La suma de @num1 y de @num2 es igual @num3</label>
<br/>
<label>@message</label>

PracticaMVC/Views/vistaRazor/bucles.cshtml
@{
    ViewBag.Title = "bucles";
    var cantidaLineas = 10;
}

<h2>bucles</h2>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @for(int i = 0; i < cantidaLineas; i++)
        {
            <tr>
                <td>@i</td>
                <td>Nombre No. @i</td>
            </tr>
        }
    </tbody>
</table>

PracticaMVC/Views/vistaRazor/condiciones.cshtml
@{
    ViewBag.Title = "condiciones";
}

@{
    var mensaje = "";
    var User = "admin";
    if (User == "admin")
    {
        mensaje = "Administrador del sistema";

    }else
    {
        mensaje = "Gestor";
    }

}
<h2>condiciones</h2>
<p>Bienvenido @mensaje</p>